name: GitHub Repository Analyzer

on:
  schedule:
    - cron: '0 0 * * *'  # Roda todo dia à meia-noite UTC
  workflow_dispatch:       # Trigger manual

permissions:
  contents: write

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests PyGithub python-dotenv

      - name: Run analyzer script
        env:
          GITHUB_TOKEN: ${{ secrets.ACESS_PAT }}
          GITHUB_ACTOR: ${{ github.actor }}
        run: |
          python scripts/generate_report.py

      - name: Commit and push report and exports
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action Bot"
          git add REPORT.md reports/
          git diff --staged --quiet || git commit -m "📊 [$(date -u '+%Y-%m-%d %H:%M:%S UTC')]"
          git push
